Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def divide(x, y): 
    try: 
        # Floor Division : Gives only Fractional Part as Answer 
        result = x // y 
        print("Yeah ! Your answer is :", result) 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 
  
# Look at parameters and note the working of Program 
divide(5, 0) 

Sorry ! You are dividing by zero 


Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

#using inner for loop
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

for sub in subject:
    for vb in verb:
        for ob in obj:
            print((sub+" "+ vb + " " + ob))

In [5]:
#using list comprehension
sent_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sent_list:
 print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [ ]:
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [13]:
import numpy as np
def vanderOutput(input):
    n = 4
    
    if(len(input) > 0):
        #output =np.vander(input,increasing=True)
        output = np.column_stack([input**(n-1-i) for i in range(n)])
    else:
        print("vector is empty")
    return output
    
x = np.array([1,2,3,4,5])
output = vanderOutput(x)
print(output)
    

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
